[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
included-patches = "'Limit feed to followed profiles' 'Hide explore feed' 'Hide navigation buttons' 'Hide Stories from Home' 'Hide suggested content' 'Enable developer menu' 'Open links externally' 'Change link sharing domain'"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Hide view count' 'Change link sharing domain'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/"

[photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

[soundcloud]
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/"

[viber]
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"
included-patches = "'Hide navigation buttons'"

